services:
  backend-server:
    image: node:18-alpine
    command: sh -c "yarn install && yarn start"
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - ./backend/:/app
      - backend:/app/node_modules/
    environment:
      - LIVEKIT_URL=ws://livekit:7880
      - WEBSOCKET_SERVER_URL=ws://websocket-server-py:8765
    depends_on:
      - livekit
  websocket-server-py:
    build: ./backend/websocket-server-py/
    ports:
      - 8765:8765
    working_dir: /app
    volumes:
      - ./backend/websocket-server-py/:/app
    environment:
      - TRANSCRIPTION_SERVER_URL=http://transcription-server:5050/
    depends_on:
      - transcription-server
#  websocket-server:
#    image: node:18-alpine
#    command: sh -c "yarn install && yarn start-wss"
#    ports:
#      - 8080
#    working_dir: /app
#    volumes:
#      - ./backend/:/app
#      - backend:/app/node_modules/
  transcription-server:
    build: ./backend/transcription-service/
    ports:
      - 5050:5050
      - 5555:5555
    working_dir: /app
    volumes:
      - ./backend/transcription-service:/app
    environment:
      - REDIS_URL=redis://redis-svc:6379
    depends_on:
      - redis-svc
  frontend:
    image: node:18-alpine
    command: sh -c "yarn install && yarn start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./frontend/:/app
      - frontend:/app/node_modules/
  
  redis-svc:
    image: redis
    ports:
      - 6379
  livekit:
    image: livekit/livekit-server
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    ports:
      - 7880:7880
    volumes:
      - ./livekit-server.yaml:/etc/livekit.yaml
    depends_on:
      - redis-svc
  livekit-egress:
    image: livekit/egress
    environment:
      - EGRESS_CONFIG_FILE=/out/config.yaml
    volumes:
      - ./livekit-egress/config.yaml:/out/config.yaml
    depends_on:
      - redis-svc


volumes:
  backend:
    driver: local
  frontend:
    driver: local